### ISSUE TITLE
support window paste event

### ISSUE THREAD

**Issue by mfulton26** [Sec-ant/zxing-wasm-demo#34]
I like the demo page. I'd love to paste an image on my clipboard to it in lieu of saving the image first to a file and then uploading it.

e.g.

```ts
window.addEventListener("paste", async ({ clipboardData: { files } }) => {
  for (const file of files) {
    const imageBitmap = await createImageBitmap(file);
    /* ... */
```

**Comment by Sec-ant** [comment]
Thank you, this is a nice to have feature. But the demo page has a relatively low priority among my on-hand works. PR is welcome.
